apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: 2-sjheo-nginx
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: 059371745111.dkr.ecr.us-east-1.amazonaws.com/product-app:2023-10-22.15.47.19
        name: 2-sjheo-nginx
        resources: {}
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            #httpHeaders:
            #- name: Custom-Header
              #value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 2
          failureThreshold: 1
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: 2-sjheo-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  type: LoadBalancer
status:
  loadBalancer: {}
